### ISSUE TITLE
每个epoch后best_val_acc的值都不变

### ISSUE THREAD

**Issue by lihe** [xv44586/toolkit4nlp#10]
![image](https://user-images.githubusercontent.com/48715622/115642158-0369b280-a34d-11eb-82cd-252f4f0d7823.png)

用classification_ifytek_bert_of_theseus.py做测试，每个epoch后best_val_acc的值都是一样的

**Comment by xv44586** [comment]
修改的部分贴出来

**Comment by lihe** [comment]
只修改了bert模型和数据集的路径，其余未做修改。

命令为
python classification_ifytek_bert_of_theseus.py

**Comment by xv44586** [comment]
代码我都是测试过的，环境跟我对齐的情况下是不会有问题的应该，模型和数据集是什么？贴出来看看

**Comment by lihe** [comment]
![image](https://user-images.githubusercontent.com/48715622/115896777-58f9a880-a48e-11eb-99fd-e792f19d3cd2.png)
这是模型和数据集


![image](https://user-images.githubusercontent.com/48715622/115896925-8181a280-a48e-11eb-8a58-35f16a6fca4a.png)
这是目录结构


测试了多次，每个epoch之后best_val_acc的值都是0.14929，没有变换

**Comment by lihe** [comment]
![image](https://user-images.githubusercontent.com/48715622/115898225-e38ed780-a48f-11eb-84b6-7b56c1d2dad1.png)
![image](https://user-images.githubusercontent.com/48715622/115898254-ec7fa900-a48f-11eb-8bc7-dfb9a88c5247.png)

我测试用的数据集是iflytek_public
我觉得可能是iflytek数据集和iflytek_public数据集可能是不同的，明天我再做做测试

**Comment by lihe** [comment]
你能提供一下iflytek数据集的下载地址吗，我下载的iflytek数据集好像不对

**Comment by xv44586** [comment]
CLUE上的公开数据
