### ISSUE TITLE
请问有具体的博客介绍您的思路吗？

### ISSUE THREAD

**Issue by effort-yq** [xv44586/toolkit4nlp#11]

**Comment by xv44586** [comment]
偶尔会写在博客里 http://xv44586.github.io/

**Comment by effort-yq** [comment]
好的，谢谢您


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xv44586/toolkit4nlp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月5日(星期一) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xv44586/toolkit4nlp] 请问有具体的博客介绍您的思路吗？ (#11)





 
偶尔会写在博客里 http://xv44586.github.io/
