### ISSUE TITLE
pretraining 麻烦咨询下预训练语料格式是？然后现在只支持robeata预训练吗

### ISSUE THREAD

**Issue by lonngxiang** [xv44586/toolkit4nlp#3]

**Comment by xv44586** [comment]
1.预训练的语料就是句子列表，具体构造方式根据自己的语料来修改preprocess.py 中的 [generator_corp](https://github.com/xv44586/toolkit4nlp/blob/master/pretraining/preprocess.py#L252)方法即可。
2.暂时是只做了roberta的方式。
3.更灵活的方式可以参考[classification_tnews_pretrain_before_finetuning.py](https://github.com/xv44586/toolkit4nlp/blob/master/examples/classification_tnews_pretrain_before_finetuning.py)
