### ISSUE TITLE
可否提供一个基于toolkit4nlp的 sentence bert 例子

### ISSUE THREAD

**Issue by sssdjj** [xv44586/toolkit4nlp#5]
大佬最近在做 sentence bert 基于toolkit4nlp整了半天不好，可否提供一个demo

**Comment by xv44586** [comment]
帮你写了一个demo：[sbert-stsb](https://github.com/xv44586/toolkit4nlp/blob/master/examples/sbert-sts-b.py)
另外如果是做相关任务，推荐你看看[BERT-whitening](https://github.com/bojone/BERT-whitening)

**Comment by sssdjj** [comment]
万分谢谢大神

**Comment by xv44586** [comment]
我自己用原论文的数据和参数试了下，得不到论文里的结果，而且我看他的代码下也有很多人有类似的问题，所以总体感觉这论文不太可靠，如果是用来做项目推荐苏神的whitening或者simbert
